### ISSUE TITLE
AttributeError as soon as I log in.

### ISSUE THREAD

**Issue by daehyok** [EcmaXp/wfapi#2]
As soon as I log in my workflowy account, I got the following error message. Could you fix it for me?

.../anaconda/lib/python3.5/site-packages/wfapi/node.py in from_vaild_json(cls, info)
33 setattr_node = super(cls, self).setattr
34 for k, v in value.items():
---> 35 setattr_node(k, v)
36
37 return self

AttributeError: 'WFRawNode' object has no attribute 'lmb'

**Comment by pauldeden** [comment]
I have the same issue and I'm running python 3.6.1 on Ubuntu.

**Comment by pauldeden** [comment]
I tried version 0.7.0 (the latest version as of today in github) and it worked with python 3.6.1 on Ubuntu.

I suspect this bug has been fixed already, but the pypi module hasn't yet been updated.  The version on pypi is listed as 0.2.0-alpha

**Comment by daehyok** [comment]
Working well with 0.7.0. Great work and thanks.

**Comment by EcmaXp** [comment]
i will upload 0.8.0, thanks!

**Comment by pauldeden** [comment]
Thanks!
